apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cve-2019-3396-db
  name: cve-2019-3396-db
  namespace: metarget
spec:
  ports:
  - name: '5432'
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: cve-2019-3396-db
status:
  loadBalancer: {}
