apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./confluence/CVE-2019-3396/docker-compose.yml
      -o RCE-FOR-K8S-4/confluence/CVE-2019-3396/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-2019-3396-db
  name: cve-2019-3396-db
  namespace: metarget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2019-3396-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./confluence/CVE-2019-3396/docker-compose.yml
          -o RCE-FOR-K8S-4/confluence/CVE-2019-3396/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cve-2019-3396-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: confluence
        - name: POSTGRES_PASSWORD
          value: postgres
        image: postgres:10.7-alpine
        imagePullPolicy: IfNotPresent
        name: cve-2019-3396-db
        ports:
          - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
